[package]
name = "collascii"
version = "0.1.0"
authors = ["Evan New-Schmidt <evan@new-schmidt.com>"]
edition = "2018"

[dependencies]
pancurses = "*"
# cursive = "*"
log = "*"
env_logger = "*"
structopt = "*"
